/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ISAPROJ_H
#define ISAPROJ_H

/* function declarations */
void init_isaProj(void);
Netsnmp_Node_Handler handle_isaLogin;
Netsnmp_Node_Handler handle_isaTime;
Netsnmp_Node_Handler handle_isaInt;
Netsnmp_Node_Handler handle_isaInfoOS;

#endif /* ISAPROJ_H */
