/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "isaProj.h"

#include <time.h>

static int isaInt = 0;
static oid isaInt_oid[] = { 1,3,6,1,3,22,3 };

static const oid isaLogin_oid[] = { 1,3,6,1,3,22,1 };
static const oid isaTime_oid[] = { 1,3,6,1,3,22,2 };
//const oid isaInt_oid[] = { 1,3,6,1,3,22,3 };
static const oid isaInfoOS_oid[] = { 1,3,6,1,3,22,4 };

/** Initializes the isaProj module */
void
init_isaProj(void)
{

  DEBUGMSGTL(("isaProj", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("isaLogin", handle_isaLogin,
                               isaLogin_oid, OID_LENGTH(isaLogin_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("isaTime", handle_isaTime,
                               isaTime_oid, OID_LENGTH(isaTime_oid),
                               HANDLER_CAN_RONLY
        ));

    // netsnmp_register_scalar(
    //     netsnmp_create_handler_registration("isaInt", handle_isaInt,
    //                            isaInt_oid, OID_LENGTH(isaInt_oid),
    //                            HANDLER_CAN_RWRITE
    //     ));
    netsnmp_register_int_instance("isaInt",
                                  isaInt_oid,
                                  OID_LENGTH(isaInt_oid),
                                  &isaInt, NULL);

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("isaInfoOS", handle_isaInfoOS,
                               isaInfoOS_oid, OID_LENGTH(isaInfoOS_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_isaLogin(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */
                                     (u_char*)"xkocal00",
                                     /* XXX: the length of the data in bytes */
                                     9);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_isaLogin\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_isaTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            ;
            //get current time
            time_t currTime;
            struct tm* timeInfo;
            time(&currTime);
            timeInfo = localtime(&currTime);

            //format it
            char strBuff[100];
            int strLen = strftime(strBuff, 100, "%FT%T%z", timeInfo);

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */
                                     (u_char*)strBuff,
                                     /* XXX: the length of the data in bytes */
                                     strLen);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_isaTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
// int
// handle_isaInt(netsnmp_mib_handler *handler,
//                           netsnmp_handler_registration *reginfo,
//                           netsnmp_agent_request_info   *reqinfo,
//                           netsnmp_request_info         *requests)
// {
//     int ret;
//     /* We are never called for a GETNEXT if it's registered as a
//        "instance", as it's "magically" handled for us.  */

//     /* a instance handler also only hands us one request at a time, so
//        we don't need to loop over a list of requests; we'll only get one. */
    
//     switch(reqinfo->mode) {

//         case MODE_GET:
//             snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
//                                      /* XXX: a pointer to the scalar's data */,
//                                      /* XXX: the length of the data in bytes */);
//             break;

//         /*
//          * SET REQUEST
//          *
//          * multiple states in the transaction.  See:
//          * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
//          */
//         case MODE_SET_RESERVE1:
//                 /* or you could use netsnmp_check_vb_type_and_size instead */
//             ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
//             if ( ret != SNMP_ERR_NOERROR ) {
//                 netsnmp_set_request_error(reqinfo, requests, ret );
//             }
//             break;

//         case MODE_SET_RESERVE2:
//             /* XXX malloc "undo" storage buffer */
//             if (/* XXX if malloc, or whatever, failed: */) {
//                 netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
//             }
//             break;

//         case MODE_SET_FREE:
//             /* XXX: free resources allocated in RESERVE1 and/or
//                RESERVE2.  Something failed somewhere, and the states
//                below won't be called. */
//             break;

//         case MODE_SET_ACTION:
//             /* XXX: perform the value change here */
//             if (/* XXX: error? */) {
//                 netsnmp_set_request_error(reqinfo, requests, /* some error */);
//             }
//             break;

//         case MODE_SET_COMMIT:
//             /* XXX: delete temporary storage */
//             if (/* XXX: error? */) {
//                 /* try _really_really_ hard to never get to this point */
//                 netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
//             }
//             break;

//         case MODE_SET_UNDO:
//             /* XXX: UNDO and return to previous value for the object */
//             if (/* XXX: error? */) {
//                 /* try _really_really_ hard to never get to this point */
//                 netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
//             }
//             break;

//         default:
//             /* we should never get here, so this is a really bad error */
//             snmp_log(LOG_ERR, "unknown mode (%d) in handle_isaInt\n", reqinfo->mode );
//             return SNMP_ERR_GENERR;
//     }

//     return SNMP_ERR_NOERROR;
// }

int
handle_isaInfoOS(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    #if defined (_WIN32) || defined (_WIN64)
        char *osStr = "Windows";
        size_t osStrLen = 8;
    #elif defined (unix) || defined (__unix) || defined (__unix__)
        char *osStr = "Unix";
        size_t osStrLen = 5;
    #endif
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */
                                     osStr,
                                     /* XXX: the length of the data in bytes */
                                     osStrLen);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_isaInfoOS\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

void
deinit_isaProj(void)
{
    unregister_mib(isaInt_oid,OID_LENGTH(isaInt_oid));
}